### PR TITLE
Proposed changes to makeBrighterFatterKernel.py

### PR DESCRIPTION
**Pull request by craiglagegit**
This pull request refers to the proposed changes to makeBrighterFatterKernel.py that I reviewed at the Berkeley DESC last week.  There are slides that review the proposed changes (Berkeley_DESC_BF_15Feb19.pdf) in the notebooks directory.  I anticipate that there will be significant discussion and requests for clarifications and improvements on this pull request, but I wanted to start the ball rolling.

### CODE REVIEW

**Comment by timj** [comment]
Two minor points. These commits have bad author email information: `cslage <cslage@ad3.ucdavis.edu@phys-emerald.ou.ad3.ucdavis.edu>`; and please remove that fake merge commit before merging to master.

**Comment by craiglagegit** [comment]
Tim, sorry to be dense, but I don't understand what I need to do.  My E-mail in my github profile is correct.  Where is that other E-mail address coming from?  Also, I don't understand what caused that 'fake merge'.  When I tried to push the slides this morning, it wouldn't let me unless I did a 'git pull' first.  I don't understand why, and I don't know how to remove the 'fake merge' .

**Comment by timj** [comment]
Ok.

1. When you commit on the command line `git` tries to guess what your email might be. You force it to the value you want in your `~/.gitconfig`. See https://developer.lsst.io/git/setup.html?highlight=gitconfig#in-git-required-configuration

2. The "fake" merge commit is one that got created when you did a `git pull` even though you had already made commits directly on master.  It's generally much easier for a fork to develop on a branch other than master so that you have more control over what is going on. In your particular case `git pull --rebase` would have fixed the problem. `git rebase origin/master` might sort you out in this case.

**Comment by craiglagegit** [comment]
I fixed the bogus E-Mail in ~/.gitconfig.  How do I proceed from here? Is there a way to kill this pull request and start over?

**Comment by isullivan** [comment]
You can amend your commits to change the author e-mail:
`git filter-branch --commit-filter '
        if [ "$GIT_AUTHOR_EMAIL" = "wrongID@bad.com" ];
        then
                GIT_AUTHOR_EMAIL="correctID@right.edu";
                git commit-tree "$@";
        else
                git commit-tree "$@";
        fi' HEAD~1..HEAD`
Afterwards you would need to force-push.

**Comment by craiglagegit** [comment]
OK, I did that.  It seemed to work.

**Comment by craiglagegit** [comment]
I cleaned up the fork, removing the unneeded optional versions.  The only version now processes all 16 amps.  I also removed the supporting notebooks and documentation.   I will put thew elsewhere.

**Comment by craiglagegit** [comment]
These changes have all been incorporated by now by Merlin Fisher-Levine and Andrés Plazas, so this can be closed.

**Pull request closed without merging**
